"""Backend contract for the BLS12-381 operations used by ``groups``.

Protocol modules continue to use the stable functions in ``groups.py``. The
backend contract is internal and contains no wire-format or protocol policy.
"""

from __future__ import annotations

from typing import Any, Protocol


class InvalidBackendInput(ValueError):
    """Input error translated to the stable public group exception by groups."""


class GroupBackend(Protocol):
    """Primitive operations required by the package's group adapter."""

    backend_name: str

    def curve_order(self) -> int: ...

    def g1_generator(self) -> Any: ...
    def g2_generator(self) -> Any: ...
    def g1_identity(self) -> Any: ...
    def g2_identity(self) -> Any: ...

    def g1_add(self, left: Any, right: Any) -> Any: ...
    def g2_add(self, left: Any, right: Any) -> Any: ...
    def g1_neg(self, point: Any) -> Any: ...
    def g2_neg(self, point: Any) -> Any: ...
    def g1_mul(self, point: Any, exponent: int) -> Any: ...
    def g2_mul(self, point: Any, exponent: int) -> Any: ...
    def g1_is_identity(self, point: Any) -> bool: ...
    def g2_is_identity(self, point: Any) -> bool: ...
    def g1_equal(self, left: Any, right: Any) -> bool: ...
    def g2_equal(self, left: Any, right: Any) -> bool: ...
    def inspect_g1(self, point: Any) -> tuple[bool, bool, bool]: ...
    def inspect_g2(self, point: Any) -> tuple[bool, bool, bool]: ...

    def encode_g1(self, point: Any) -> bytes: ...
    def encode_g2(self, point: Any) -> bytes: ...
    def decode_g1(self, data: bytes) -> Any: ...
    def decode_g2(self, data: bytes) -> Any: ...

    def pairing(self, g1_point: Any, g2_point: Any) -> Any: ...
    def pairing_miller(self, g1_point: Any, g2_point: Any) -> Any: ...
    def pairing_product_miller(
        self, terms: list[tuple[Any, Any, int]]
    ) -> Any: ...
    def pairing_product_is_identity(
        self, terms: list[tuple[Any, Any, int]]
    ) -> bool: ...

    def gt_final_exponentiate(self, value: Any) -> Any: ...
    def gt_identity(self) -> Any: ...
    def gt_equal(self, left: Any, right: Any) -> bool: ...
    def gt_mul(self, left: Any, right: Any) -> Any: ...
    def gt_inv(self, value: Any) -> Any: ...
    def gt_pow(self, value: Any, exponent: int) -> Any: ...

    def hash_to_g1(self, message: bytes, dst: bytes) -> Any: ...
    def hash_to_g2(self, message: bytes, dst: bytes) -> Any: ...
